### PR TITLE
Now with unit test

### PR DESCRIPTION
**Pull request by sheeley**

### CODE REVIEW

**Comment by natelyman** [comment]
:+1: :hankey:

**Comment by sheeley** [comment]
screen shot 2015-05-22 at 6 08 57 pm

**Comment by kirktrue** [comment]
+1. Thanks!

**Comment by sheeley** [comment]
fine.

**Comment by kirktrue** [comment]
Why was this closed? User requirements change? Using MongoDB at Fanatics now?

**Comment by sheeley** [comment]
fine.

**Pull request closed without merging**
